### PR TITLE
feat: list repos on homepage

### PR DESCRIPTION
**Pull request by bennypowers**
Add new repos to `_data/repos.yaml`. They're randomly chosen each build and the first five are displayed. the details are fetched from github on the _client-side_. we can choose down the line to reimplement the web component here and fetch data server side, but IMHO that's neither a blocker or necessarily the ideal choice. what might be nice though would be paginating the results instead of picking randomly. we have `<rh-pagination>` now, too

### CODE REVIEW

**Comment by bennypowers** [comment]
@TomerFi what can we do about the rate limits? https://github.com/RedHat-Israel/red-hat-israel-site/actions/runs/3403869880/jobs/5660801371

**Comment by TomerFi** [comment]
> @TomerFi what can we do about the rate limits? https://github.com/RedHat-Israel/red-hat-israel-site/actions/runs/3403869880/jobs/5660801371

@bennypowers although we have a better chance of hitting this limit because we use my own token.
even if would use a dedicated user, we still might hit this.
For a quick solution, we can wait a while for the pipe to free up and re-run the failed workflows,
I just did it for this PR and it worked (I noticed you tried, probably didn't waited enough :-) ).

For a more robust solution, we can add another token from another user and spread our requests.
Let's talk about this in our next meeting.

**Comment by TomerFi** [comment]
@bennypowers 
looks like this PR messed something in arrangement in the main page.

Before this PR:
image

From the Preview site:
image

**Comment by TomerFi** [comment]
I also think that:
"בשנה האחרונה..."
should have the same font properties as:
"מהפרויקטים שאנחנו תורמים אליהם..."

**Comment by bennypowers** [comment]
please take another look

**Comment by TomerFi** [comment]
lgtm

**Review by TomerFi — APPROVED** [review]

**Pull request merged**
