### PR TITLE
chore: fix path prefix

### PR DESCRIPTION
**Pull request by bennypowers**
fixes for 11ty path prefix

### CODE REVIEW

**Comment by TomerFi** [comment]
@bennypowers 
Will this work when serving the site locally for debugging and `ELEVENTY_PATH_PREFIX` is not set?

**Comment by bennypowers** [comment]
no we should check for github actions env stuff in the config script

but we can do that in a subsequent pr if you like

**Comment by TomerFi** [comment]
This is cool, it works locally too, it just adds the `red-hat-israel-site` endpoint:
But we need to set the env var for the pr workflow.

**Comment by bennypowers** [comment]
https://github.com/RedHat-Israel/red-hat-israel-site/blob/81703fc36d14289b55e58b3b5dfa1990f1463993/.github/workflows/pr.yml#L29-L30

**Comment by bennypowers** [comment]
:shipit:

**Comment by TomerFi** [comment]
> https://github.com/RedHat-Israel/red-hat-israel-site/blob/81703fc36d14289b55e58b3b5dfa1990f1463993/.github/workflows/pr.yml#L29-L30

I just saw that and came back to update my comment.
😄

**Pull request merged**
